# Generated by Django 5.0.1 on 2025-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='most_popular_words',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=50)),
                ('grammar', models.CharField(max_length=25)),
                ('mutiple_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('audio', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('translated_description', models.JSONField()),
                ('category', models.CharField(choices=[('business', 'business'), ('culture', 'culture'), ('food', 'food'), ('hospital', 'hospital'), ('banking', 'banking'), ('job culture', 'job culture'), ('conversation', 'conversation'), ('questions', 'questions')], default='other', max_length=50)),
                ('mutiple_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('audio', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('profile', models.CharField(default='john doe', max_length=50)),
                ('category', models.ManyToManyField(blank=True, to='main.question')),
                ('most_popular_words', models.ManyToManyField(blank=True, to='main.most_popular_words')),
            ],
        ),
    ]
