# Generated by Django 5.0.1 on 2025-03-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='most_popular_words',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('translation', models.CharField(max_length=50)),
                ('grammar', models.CharField(max_length=50)),
                ('mutiple_choice', models.CharField(choices=[('A', 'apple'), ('B', 'banana'), ('C', 'orange'), ('D', 'pear')], max_length=50)),
                ('audio', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('translated_description', models.JSONField()),
                ('category', models.CharField(choices=[('business', 'business'), ('culture', 'culture'), ('food', 'food'), ('hospital', 'hospital'), ('banking', 'banking'), ('job culture', 'job culture'), ('conversation', 'conversation'), ('questions', 'questions')], default='other', max_length=50)),
                ('mutiple_choice', models.CharField(choices=[('A', 'apple'), ('B', 'banana'), ('C', 'orange'), ('D', 'pear')], max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('audio', models.BinaryField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default='john doe', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='most_popular_words',
            field=models.ManyToManyField(blank=True, to='main.most_popular_words'),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.question'),
        ),
    ]
