# Generated by Django 5.0.1 on 2025-03-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_most_popular_words_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AlterField(
            model_name='most_popular_words',
            name='grammar',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='most_popular_words',
            name='mutiple_choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='mutiple_choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50),
        ),
    ]
