# Generated by Django 5.0.1 on 2025-07-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_most_popular_words_grammar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='most_popular_words',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
