# Generated by Django 5.0.1 on 2025-07-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_most_popular_words_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='most_popular_words',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
